namespace Sentyll.Domain.Common.Extensions;

public static class StringExtensions
{
    public static string AsRelativeResource(this string resourcePath)
    {
        return resourcePath.StartsWith("/") ? resourcePath.Substring(1) : resourcePath;
    }
    
    /// <summary>
    /// Parse the input string by placing a space between character case changes in the string
    /// </summary>
    /// <remarks>
    /// This extension method was fully generated by uncle ChatGPT :)
    /// I without hesitation, just copy and pasted it and hey it worked sooo...
    /// Bananas for everyone.
    /// </remarks>
    /// <param name="strInput">The string to parse</param>
    /// <returns>The altered string</returns>
    public static string ParseByCase(this string strInput)
    {
        // The altered string (with spaces between the case changes)
        string strOutput = "";

        // The index of the current character in the input string
        int intCurrentCharPos = 0;

        // The index of the last character in the input string
        int intLastCharPos = strInput.Length - 1;

        // for every character in the input string
        for (intCurrentCharPos = 0; intCurrentCharPos <= intLastCharPos; intCurrentCharPos++)
        {
            // Get the current character from the input string
            char chrCurrentInputChar = strInput[intCurrentCharPos];

            // At first, set previous character to the current character in the input string
            char chrPreviousInputChar = chrCurrentInputChar;

            // If this is not the first character in the input string
            if (intCurrentCharPos > 0)
            {
                // Get the previous character from the input string
                chrPreviousInputChar = strInput[intCurrentCharPos - 1];
            }

            // Put a space before each upper case character if the previous character is lower case
            if (char.IsUpper(chrCurrentInputChar) == true && char.IsLower(chrPreviousInputChar) == true)
            {   
                // Add a space to the output string
                strOutput += " ";
            }

            // Add the character from the input string to the output string
            strOutput += chrCurrentInputChar;
        }

        // Return the altered string
        return strOutput;
    }
}
